version: '3.7'

services:
  php-apache:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ungexternaldatabseurlmo.oregon-postgres.render.com
      DB_PORT: 5432
      DB_NAME: databsasee
      DB_USER: todo_32kx_user     
      DB_PASSWORD: passwordmo   
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  app-network:
    driver: bridge